### ISSUE TITLE
Ensure hyperv generation of images matches VMSS VM generation

### ISSUE THREAD

**Issue by jackfrancis** [jackfrancis/kamino#91]
We want to detect which hyperv generation the VMSS is built on top of, and then update the `az sig image-definition create` command accordingly:

```
$ az sig image-definition create --help | grep generation
Please let us know how we are doing: https://aka.ms/azureclihats
    --hyper-v-generation                     : The hypervisor generation of the Virtual Machine.
```

**Comment by Michael-Sinz** [comment]
We just need to pick the generation that matches the VMSS instance.  Sounds like a very reasonable thing to do.
